m7_python/urls.py
from django.urls import path
from .views import (indexView, RegisterView, ContactView, register_rol, welcome,
                    profile_view, about, edit_profile_view, index_arrendatario, 
                    dashboard_arrendador, not_authorized_view, create_inmueble, 
                    edit_inmueble, detail_inmueble, delete_inmueble, 
                    edit_disponibilidad_inmueble, send_solicitud, view_list_user_solicitudes, view_list_solicitudes,
                    edit_status_solicitud)

urlpatterns = [
    path('', indexView, name='index'),
    path('not_authorized/', not_authorized_view, name='not_authorized'),
    path('accounts/register', RegisterView, name='register'),
    path('contacto/', ContactView.as_view(), name='contact'),
    path('accounts/register_rol', register_rol, name='register_rol'),
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', edit_profile_view, name='edit_profile'),
    path('about/', about, name='about'),
    path('welcome/index.html', welcome, name='welcome'),
        # TODO__ PATH (urls - ROUTES) - ARRENDATARIO
    path('index', index_arrendatario, name='index_arrendatario'),
    path('inmueble/solicitar/<int:inmueble_id>/', send_solicitud, name='send_solicitud'),
    path('list/solicitudes/', view_list_user_solicitudes, name='solicitudes'),
#___________________________________________________________________________________________________
#███████████████████████████████████████████████████████████████████████████████████████████████████

    # TODO__ PATH (urls - ROUTES) - ARRENDADOR
    path('dashboard', dashboard_arrendador, name="dashboard_arrendador"),
    path('dashboard/create', create_inmueble, name="create_inmueble"),
    path('dashboard/inmueble/edit/<int:inmueble_id>/',edit_inmueble, name='edit_inmueble'),
    path('dashboard/detail/<int:inmueble_id>/', detail_inmueble, name="detail_inmueble"),
    path('dashboard/inmueble/delete/<int:inmueble_id>/',delete_inmueble, name='delete_inmueble'),
    path('dashboard/inmueble/disponibilidad/<int:inmueble_id>/', edit_disponibilidad_inmueble, name='edit_disponibilidad_inmueble'),
    path('dashboard/inmueble/solicitudes/<int:inmueble_id>/', view_list_solicitudes, name='view_list_solicitudes'),
    path('dashboard/solicitud/edit-status/<int:solicitud_id>/', edit_status_solicitud, name='edit_status_solicitud')
    
    
]

project_M7/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('m7_python.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]



"""
accounts/ login/ [name='login'] * <- def login() -> render login.html, {user: dta}
accounts/ logout/ [name='logout']
accounts/ password_change/ [name='password_change']
accounts/ password_change/done/ [name='password_change_done']
accounts/ password_reset/ [name='password_reset']
accounts/ password_reset/done/ [name='password_reset_done']
accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
accounts/ reset/done/ [name='password_reset_complete']
"""

m7_python/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

# Create your models here.

class UserProfile(models.Model):
    tipos = (('arrendador', 'Arrendador'), ('arrendatario', 'Arrendatario'))
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    rut = models.CharField(max_length=9, unique=True)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15, null=True, blank=True)
    tipo = models.CharField(max_length=255, choices=tipos, default='arrendatario')
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} ({self.tipo})'
    
class Region(models.Model):
    cod = models.CharField(max_length=2, primary_key=True)
    nombre = models.CharField(max_length=255)
    def __str__(self) -> str:
        return f'{self.nombre} ({self.cod})'
    
    
class Comuna(models.Model):
    cod = models.CharField(max_length=5, primary_key=True)
    nombre = models.CharField(max_length=255)
    region = models.ForeignKey(Region, related_name='comunas', on_delete=models.RESTRICT) 
    def __str__(self) -> str:
        return f'{self.nombre} ({self.cod})'      


class Inmueble(models.Model):
    TIPOS = (('casa', 'Casa'), ('departamento', 'Departamento'), ('bodega', 'Bodega'), ('parcela', 'Parcela'))
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=1500)
    m2_construidos = models.IntegerField(validators=[MinValueValidator(1)])
    m2_totales = models.IntegerField(validators=[MinValueValidator(1)])
    num_estacionamientos = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    num_habitaciones = models.IntegerField(validators=[MinValueValidator(1)], default=1)
    num_baños = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    direccion = models.CharField(max_length=255)
    tipo_inmueble = models.CharField(max_length=255, choices=TIPOS)
    precio = models.IntegerField(validators=[MinValueValidator(1000)], null=True)
    precio_ufs = models.FloatField(validators=[MinValueValidator(1.0)], null=True)
    disponible = models.BooleanField(default=True)
    #* UF se utiliza para ajustar los valores de contratos, precios y pagos para reflejar cambios en la inflación.
    #TODO_ FKs - llaves foráneas - 1:N
    comuna = models.ForeignKey(Comuna, related_name='inmuebles', on_delete=models.RESTRICT)
    arrendador = models.ForeignKey(User, related_name='inmuebles', on_delete=models.RESTRICT)
    #* arrendador - propietario es un USER de de tipo rol 'arrendador' en el UserProfile
    
    
class Solicitud(models.Model):
    ESTADOS = (('pendiente', 'Pendiente'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada'), ('finalizada', 'Finalizada'))
    inmueble = models.ForeignKey(Inmueble, related_name='solicitudes', on_delete=models.CASCADE)
    arrendatario = models.ForeignKey(User, related_name='solicitudes_arrendatario', on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=50, choices=ESTADOS, default='pendiente')
    
  
  
  
# MODEL CONTACTO
class ContactForm(models.Model):
    customer_email = models.EmailField()
    customer_name = models.CharField(max_length=64)
    message = models.TextField()
    
    def __str__(self):
        return self.customer_name    
class Contact(models.Model):
	nombre = models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	mensaje = models.CharField(max_length=500)
		  
	def __str__(self):
		name = self.nombre
		message = self.mensaje
		return f'{name} : {message}'

# class ContactForm(models.Model):
#     contact_form_uuid = models.UUIDField(default=uuid.uuid4, editable=False)
#     customer_email = models.EmailField()
#     customer_name = models.CharField(max_length=64)
#     message = models.TextField()
    
# def __str__(self):
#     return self.customer_name

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE) # -> asocición - relación
#     bio = models.TextField(max_length=500, blank=True) # el campo puede estar vacío
#     location = models.CharField(max_length=30, blank=True)
#     birth_date = models.DateField(null=True, blank=True) # generalmente YYYY-MM-DD (por ejemplo, 2024-08-17).
#     def __str__(self):
#         return self.user.username   
# """
# c. Operaciones CRUD con Django ORM
# Crear un objeto con el modelo:

# nuevo_inmueble = Inmueble(
#     nombre="Casa en el centro",
#     descripcion="Hermosa casa de 3 habitaciones en el centro de la ciudad.",
#     m2_construidos=120.50,
#     m2_terreno=150.00,
#     numero_estacionamientos=2,
#     numero_baños=2,
#     numero_habitaciones=3,
#     direccion="Calle Principal 123",
#     id_comuna=Comuna.objects.get(id_comuna=1),
#     id_region=Region.objects.get(id_region=1),
#     tipo_inmueble="Casa",
#     precio_mensual=750.00,
#     estado="Disponible",
#     id_user=User.objects.get(id_user=1)
# )
# nuevo_inmueble.save()


# Enlistar desde el modelo de datos:

# inmuebles = Inmueble.objects.all()
# for inmueble in inmuebles:
#     print(inmueble.nombre, inmueble.precio_mensual)


# Actualizar un registro en el modelo de datos:

# inmueble = Inmueble.objects.get(id_inmueble=1)
# inmueble.precio_mensual = 800.00
# inmueble.save()


# Borrar un registro del modelo de datos:

# inmueble = Inmueble.objects.get(id_inmueble=1)
# inmueble.delete()

    
# """

m7_python/forms.py
from django import forms
from django.forms import ModelForm
from m7_python.models import ContactForm, UserProfile, Inmueble, Contact, Solicitud
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User




class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text='Requerido. Ingrese una dirección de correo electrónico válida.')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo electrónico ya está en uso.")
        return email

class ContactModelForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['nombre', 'email', 'mensaje']
        labels = {
            'nombre': 'Nombre:',
            'Email': 'email',
            'mensaje': 'Mensaje'
        }
        widgets = {
            'nombre': forms.TextInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'ej. Ruben Ramírez',
                }
            ),
            'email': forms.EmailInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'ej. ruben@mail.com'
                }
            ),
            'mensaje': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 4,
                    'placeholder': 'Máximo 500 carácteres'
                }
            )
        }   


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['rut', 'direccion', 'telefono', 'tipo']

#TODO_ EDIT PROFILE -FORM
# UserProfileForm - este form nos va a servir además para cuando vayamos a editar el perfil
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
class UserEditProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['rut', 'direccion', 'telefono', 'tipo']
        # fields = ['rut', 'direccion', 'telefono'] --> quitar tipo para solucionar problema de guardar edicion de tipo de usuario



#TODO__ FORM INMUEBLE - CREAR 
class InmuebleForm(forms.ModelForm):
    class Meta: 
        model = Inmueble
        fields = [
            'nombre', 'descripcion', 'm2_construidos', 'm2_totales',
            'num_estacionamientos', 'num_habitaciones', 'num_baños',
            'direccion', 'tipo_inmueble', 'precio', 'disponible',
            'comuna'
        ]  
        
        
        
#TODO__ FORM DISPONIBILIDAD  

class EditDisponibilidadForm(forms.ModelForm):
    class Meta:
        model = Inmueble
        fields = ['disponible']  # Solo permitimos modificar la disponibilidad
        widgets = {
            'disponible': forms.CheckboxInput(),  # Input como checkbox (disponible o no)
        }
        
        
#TODO__ FORM SOLICITUDES 
class UpdateSolicitudEstadoForm(forms.ModelForm):
    class Meta:
        model = Solicitud
        fields = ['estado']
        widgets = {
            'estado': forms.Select(choices=Solicitud.ESTADOS)  # ChoiseField basado en el modelo
        }         

m7_python/templates/about.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="col-12 col-md-6 offset-0 offset-md-3 mt-4 mb-4">
    <h3 class="text-center">Quienes somos</h3>
    <p class="text-center">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
    </p>
    <p class="text-center">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
    </p>
  </div>
</div>
{% endblock %}

m7_python/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="Rubén Mario" />
    <meta name="description" content="Página de Arriendo de Inmuebles" />
    <meta name="keywords" content="...." />

    <title>Bienvenido a "Arriendo de Inmuebles</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"/>
    <link rel="shortcut icon" href="{% static 'img/favico.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  <body style="background-color: bisque;">
    <header>
      <div class="container-fluid" style="background-color: #212529">
      <img src="{% static 'img/favico.png' %}" alt="logo" class="img-fluid mt-4 mb-4"  width=100px;
      height=50px; />
    </div>
      {% block navbar %} {% include 'navbar.html' %} {% endblock %}
    </header>

  {% if user.is_authenticated and user.user_profile.tipo == 'arrendatario' and request.path == '/index' %}
    {% block filtros %}
    {% include 'filtros/nav_filtros.html' %}
    {% endblock %}
    {% endif %}

    {% block message%} {% if messages %} {% for message in messages %}
    <div class="row">
      <div class="col">
        <div
          class="alert alert-{{ message.tags }} alert-dismissible fade show"
          role="alert"
        >
          <strong>{{ message }}</strong>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
      </div>
    </div>
    {% endfor %} {% endif %} {% endblock %}

    <main>
    {% block content %} Contenido que se actualiza en cada página {% endblock%}
    </main>

    <footer>
      {% block footer %} {% include 'snippets/footer.html' %} {% endblock %}
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block js %} {% endblock %}
  </body>
</html>

m7_python/templates/contact.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
  <h1>Contacto</h1>
  <p class="mb-4">
    Puedes escribirnos en caso que tengas cualquier duda o requerimiento.
  </p>
  <div class="row">
    <div class="col-6">
      <form action="{% url 'contact' %}" method="post">
        {% csrf_token %}
        <div class="row">
          <div class="col">{{ form.nombre.label_tag }} {{ form.nombre }}</div>
          <div class="col">{{ form.email.label_tag }} {{ form.email}}</div>
          <div class="my-3">
            {{ form.mensaje.label_tag }} {{ form.mensaje }}
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

m7_python/templates/detail_inmueble.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container px-3 text-center py-5 my-5">
    <div class="row justify-content-center mb-5">
        <!-- Imagen del inmueble -->
        <div class="col-12 col-md-8 px-0 shadow-lg">
            <!-- Usa una URL de imagen estática o un campo de imagen si está disponible -->
            <img class="img-fluid w-100" src="https://definicion.de/wp-content/uploads/2010/12/casa.jpg" alt="{{ inmueble.nombre }}">
            <!-- <img class="img-fluid w-100" src="{% static 'images/default_inmueble.jpg' %}" alt="{{ inmueble.nombre }}"> -->
        </div>
        <div class="col-12 col-md-8 text-center d-flex flex-column px-0 shadow-lg mt-4">
            <div class="border-bottom border-info py-3">
                <span class="fw-bold h1">
                    {{ inmueble.nombre }}
                </span>
            </div>
            <p class="fs-6 flex-grow-1 text-end px-2">{{ inmueble.descripcion }}</p>
            <p class="fs-6 flex-grow-1 text-end px-2">Región: <strong>{{ inmueble.comuna.region.nombre }}</strong> 
                - Comuna: <strong>{{ inmueble.comuna.nombre }}</strong></p>
            <div class="mt-auto">
                <!-- Aquí puedes mostrar precios en formato deseado -->
                <p class="fs-4 flex-grow-1 my-0" style="background-color: rosybrown;">$ {{ inmueble.precio }}</p>
                <p class="fs-4 fw-bold my-0" style="background-color:rosybrown;">Estacionamiento/s {{ inmueble.num_estacionamientos }}</p>
                <p class="fs-4 fw-bold my-0" style="background-color: rosybrown;">Habitaciones {{ inmueble.num_habitaciones }}</p>
                <p class="fs-4 fw-bold my-0" style="background-color: rosybrown;">Baños {{ inmueble.num_baños }}</p>
                <p class="fs-4 fw-bold my-0" style="background-color: rosybrown;">Dirección: {{ inmueble.direccion }}</p>
                <p class="fs-4 fw-bold my-0" style="background-color: rosybrown;">Tipo {{ inmueble.get_tipo_inmueble_display }}</p>
            </div>

            {% if user.is_authenticated and user.user_profile.tipo == 'arrendador' %}
            <a href="{% url 'edit_disponibilidad_inmueble' inmueble_id=inmueble.id %}" class="btn btn-secondary my-2">
                Cambiar Disponibilidad
            </a>
            <a href="{% url 'view_list_solicitudes' inmueble_id=inmueble.id %}" class="btn btn-secondary my-2">
                Ver Solicitudes
            </a>
                 
            
            {% endif %}
            {% if user.is_authenticated and user.user_profile.tipo == 'arrendatario' %}
                {% if inmueble.solicitudes_filtradas.exists %}
                    <div class="card-footer bg-success text-white text-center">
                        <p class="mb-0">Ya solicitado</p>
                    </div>
                {% else %}
                    <a href="{% url 'send_solicitud' inmueble_id=inmueble.id %}" class="btn btn-warning my-2">Solicitar</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <a href="{% url 'index' %}" class="w-25 btn btn-dark py-2 fw-bold mt-2"><i class="fa-solid fa-house"></i> Volver a Inicio</a>
</div>
{% endblock %}

m7_python/templates/index.html
{% extends 'base.html' %} {% block content %}
<h2 style="text-align: center">Página Web de Arriendos de Inmuebles</h2>
<div class="container mt-5">
  <div class="row">
    {% for i in inmuebles %}
    <div class="col-md-4 mb-4">
      <div class="card">
        <img
          src="https://definicion.de/wp-content/uploads/2010/12/casa.jpg"
          class="card-img-top"
          alt="Imagen de inmueble"
        />
        <div class="card-body">
          <h5 class="card-title">{{ i.nombre }}</h5>
          <p class="card-text">{{ i.descripcion }}</p>
          <p class="card-text">{{ i.comuna.nombre }}</p>
        </div>
      </div>
    </div>
    {% endfor %} 
{% endblock %}
  </div>
</div>

m7_python/templates/navbar.html
<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary mb-3"> -->
<nav class="navbar navbar-expand-lg bg-dark mb-3" data-bs-theme="dark">
  <div class="container d-flex flex-wrap">
    <a class="navbar-brand" href="{% url 'index' %}">ARRIENDOS.COM</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'index' %}"
            >Inicio</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'welcome' %}">Bienvenido</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">Acerca</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contacto</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">
            <p>Bienvenido <strong>{{ user.username }}</strong></p>
          </a>
        </li>
        <li class="nav-item">
          <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-outline-danger" type="submit">Salir</button>
          </form>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'login' %}" class="btn btn-outline-success btn-sm"
            >Ingresa</a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url 'register' %}"
            class="btn btn-outline-success btn-sm ms-2"
            >Regístrate</a
          >
        </li>
        {% endif %}

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated and user.user_profile.tipo == 'arrendador' %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'create_inmueble' %}">
              Crear Inmueble
            </a>
          </li>
          {% endif %}
          {% if user.is_authenticated and user.user_profile.tipo == 'arrendatario' %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'solicitudes' %}">
              Ver Lista de Solicitudes
            </a>
          </li>
          {% endif %}  
      </ul>
    </div>
  </div>
</nav>

m7_python/templates/not_authorized.html
{% extends 'base.html' %}    
{% block content %}
<section class="container-fluid py-4">
    <div class="card card-custom-bg py-4 px-3">
        <div class="text-center">
            <h2>No tienes acceso a esta página.</h2>
            <a href="/"><button class = "btn btn-outline-info custom">Volver a la página principal</button></a>
        </div>
    </div>
</section>
{% endblock content %}

m7_python/templates/profile_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Información Personal</h5>
      <p class="card-text"><strong>Username:</strong> {{ user.username }}</p>
      <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
      <p class="card-text"><strong>Nombre:</strong> {{ user.first_name }}</p>
      <p class="card-text"><strong>Apellido:</strong> {{ user.last_name }}</p>
      <p class="card-text"><strong>RUT:</strong> {{ profile.rut }}</p>
      <p class="card-text">
        <strong>Dirección:</strong> {{ profile.direccion }}
      </p>
      <p class="card-text"><strong>Teléfono:</strong> {{ profile.telefono }}</p>
      <p class="card-text">
        <strong>Tipo de usuario:</strong> {{ profile.tipo | upper }}
      </p>
      <a href="{% url 'edit_profile' %}" class="btn btn-primary mt-3"
        >Editar Perfil</a
      >
    </div>
  </div>
</div>
{% endblock %}

m7_python/templates/profile_edit.html
{% extends 'base.html' %} {% block content %}
<div class="container mt-5">
  <h2 class="mb-4">Editar Perfil</h2>
  <div class="card">
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="id_first_name" class="form-label">Nombre:</label>
          {{ user_form.first_name }} {{ user_form.first_name.errors }}
        </div>
        <div class="mb-3">
          <label for="id_last_name" class="form-label">Apellido:</label>
          {{ user_form.last_name }} {{ user_form.last_name.errors }}
        </div>
        <div class="mb-3">
          <label for="id_email" class="form-label">Email:</label>
          {{ user_form.email }} {{ user_form.email.errors }}
        </div>
        <div class="mb-3">
          <label for="id_rut" class="form-label">RUT:</label>
          {{ profile_form.rut }} {{ profile_form.rut.errors }}
        </div>
        <div class="mb-3">
          <label for="id_direccion" class="form-label">Dirección:</label>
          {{ profile_form.direccion }} {{ profile_form.direccion.errors }}
        </div>
        <div class="mb-3">
          <label for="id_telefono" class="form-label">Teléfono:</label>
          {{ profile_form.telefono }} {{ profile_form.telefono.errors }}
        </div>
        <input type="text" class="form-control" value="{{ tipo }}" disabled />
        <div hidden>{{ profile_form.tipo }}</div>
        <div class="mb-3">
          <label for="id_tipo" class="form-label"
            >Tipo de usuario:
            <strong>{{ user.user_profile.tipo | upper }}</strong></label
          >
        </div>
        <div class="mb-3">
          <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}